"""Initial weather table

Revision ID: 84d082633c32
Revises: 
Create Date: 2025-06-05 16:52:05.059080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d082633c32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cloud', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Enum('N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW', name='winddirection'), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('air_quality_PM2_5', sa.Float(), nullable=True),
    sa.Column('air_quality_PM10', sa.Float(), nullable=True),
    sa.Column('air_quality_Carbon_Monoxide', sa.Float(), nullable=True),
    sa.Column('air_quality_Ozone', sa.Float(), nullable=True),
    sa.Column('air_quality_Nitrogen_dioxide', sa.Float(), nullable=True),
    sa.Column('air_quality_Sulphur_dioxide', sa.Float(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
